Repository IHE/DEV.SDPi, pull requests merged in 2023-04, with the labels that each got.

#120 Updated R8118 (added comma before which)
  asciidoc/volume2/gateways/tf2-ch-b-gateway-msh-mapping.adoc
Labels: Gateway, SDPi 1.0

#104 Reworked OBR-7 and OBR-8 mapping requirements.
  asciidoc/volume2/gateways/tf2-ch-b-gateway-dec.adoc
Labels: Volume 2, Gateway, SDPi 1.0

#123 111 ihe dcc public comment review
  asciidoc/images/vol1-diagram-sdpi-a-actor.svg
  asciidoc/volume0/tf0-ch-a-actors.adoc
  asciidoc/volume1/tf1-ch-11-sdpi-r.adoc
  asciidoc/volume1/tf1-ch-12-sdpi-a.adoc
  asciidoc/volume2/dev-23/tf2-dev-23-summary.adoc
  asciidoc/volume2/dev-24/tf2-dev-24-summary.adoc
  asciidoc/volume2/dev-25/tf2-dev-25-summary.adoc
  asciidoc/volume2/dev-27/tf2-dev-27-summary.adoc
  asciidoc/volume2/dev-28/tf2-dev-28-summary.adoc
  asciidoc/volume2/dev-29/tf2-dev-29-summary.adoc
  asciidoc/volume2/dev-30/tf2-dev-30-summary.adoc
  asciidoc/volume2/dev-34/tf2-dev-34-summary.adoc
  asciidoc/volume2/dev-35/tf2-dev-35-summary.adoc
  asciidoc/volume2/dev-36/tf2-dev-36-summary.adoc
  asciidoc/volume2/dev-37/tf2-dev-37-summary.adoc
  asciidoc/volume2/dev-37/tf2-dev-37.adoc
  asciidoc/volume2/dev-38/tf2-dev-38-summary.adoc
  asciidoc/volume2/dev-39/tf2-dev-39-summary.adoc
  asciidoc/volume2/dev-40/tf2-dev-40-summary.adoc
  asciidoc/volume2/dev-40/tf2-dev-40.adoc
  sources/vol1-diagram-sdpi-a-actor.pptx
Labels: Comment Review

#124 Added PUML Diagrams to -R, -A, -xC
  asciidoc/plantuml/vol1-figure-sdpi-a-delegation-example-sequence-diagram.puml
  asciidoc/plantuml/vol1-figure-sdpi-a-reporting-example-sequence-diagram.puml
  asciidoc/plantuml/vol1-figure-sdpi-r-example-sequence-diagram.puml
  asciidoc/plantuml/vol1-figure-sdpi-xc-example-sequence-diagram.puml
  asciidoc/volume1/tf1-ch-10-sdpi-p.adoc
  asciidoc/volume1/tf1-ch-11-sdpi-r.adoc
  asciidoc/volume1/tf1-ch-12-sdpi-a.adoc
  asciidoc/volume1/tf1-ch-13-sdpi-xc.adoc
Labels: Comment Public

#125 68 general 1.0 updates from public comment
  asciidoc/sdpi-supplement-intro.adoc
  asciidoc/volume0/tf0-ch-a-actors.adoc
  asciidoc/volume0/tf0-ch-d-glossary.adoc
  asciidoc/volume0/tf0-main.adoc
  asciidoc/volume1/tf1-ch-2-overview.adoc
  asciidoc/volume2/dev-x-default-ses-secured-mode.adoc
  asciidoc/volume2/dev-x-default-ses-unsecured-mode.adoc
Labels: Comment Public

#138 Corrected SDPi-A PUML Example File
  asciidoc/volume1/tf1-ch-12-sdpi-a.adoc
Labels: SDPi 1.x, Spec, Fix Spec

#140 139 remove highlighting in closed issues section
  CHANGELOG.md
  asciidoc/sdpi-supplement-issues.adoc
Labels: Fix Spec
